### DISCUSSION TITLE
Is FUXA support subdirectory deployment?

### DISCUSSION THREAD

**Discussion by ChimingLiu** [frangoteam/FUXA#1471] [Q&A]
I want to visit FUXA in http://localhost:1881/myPath/home

**Comment by mauroalexandre** [comment]
Try using a WebServer (for example, Nginx) and use ProxyPass.

The configuration is quite simple to set up; see [here](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/).

**Comment by timmpo** [comment]
Write a comment if somebody succeed with Nginx and subdirectorys, i have had bad luck to succeed with that.
Sub domains and Nginx i have no problem with.

**Comment by mauroalexandre** [comment]
@unocelli @timmpo 

We are indeed facing an issue when using a sub-path for Fuxa.

I created a `docker-compose` for testing this scenario. It installs Docker for both Fuxa and Nginx, setting up a `proxypass` for the sub-path `/MY-SUB-PATH/`.

When we run this setup, the frontend assets are not found. This issue can be easily resolved by implementing the change I previously suggested ([link to issue](https://github.com/frangoteam/FUXA/issues/1036)), which involves removing the `/` from the base `href` in the `index.html` file. In my local project, I include this replacement step in my Docker build.

However, there is still a second issue: the frontend attempts to access `socket.io` while ignoring the sub-path.


**docker-compose.yml**

```
version: '3.9'
services:
  fuxa:
    image: frangoteam/fuxa:latest
    container_name: fuxa
    ports:
      - "1881:1881"
    environment:
      - NODE_ENV=production
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - fuxa
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    restart: always

configs:
  nginx_config:
    file: ./nginx.conf

```

**nginx.conf**

```
worker_processes 1;
events {
  worker_connections 1024;
}

http {
  server {
    listen 80;

    location /MY-SUB-PATH/ {
      proxy_pass http://fuxa:1881/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}

```
