### ISSUE TITLE
[BUG] Fuxa Electron Application not working

### ISSUE THREAD

**Issue by antwal** [frangoteam/FUXA#1266]
**Describe the bug**

**To Reproduce**

Docker Compose
```
version: "3.9"
services:
  fuxa:
    image: frangoteam/fuxa:latest
    networks:
      - blackhole
    container_name: fuxa
    volumes:
      - /mnt/storage/fuxa/appdata:/usr/src/app/FUXA/server/_appdata
      - /mnt/storage/fuxa/db:/usr/src/app/FUXA/server/_db
      - /mnt/storage/fuxa/logs:/usr/src/app/FUXA/server/_logs
      - /mnt/storage/fuxa/images:/usr/src/app/FUXA/server/_images
    ports:
      - 1881:1881
    restart: unless-stopped

networks:
  blackhole:
    name: container-net
    external: true
```

## Server:
[npm install](https://pastebin.com/Bpw0rqJa)

## Client:
[npm install](https://pastebin.com/1SGbMzbQ)
[npm run build](https://pastebin.com/C6yL6f8f)

## App
[npm install](https://pastebin.com/y6KQ2tB1)
[npm run package](https://pastebin.com/cXpzsXPz)

by default the x86_64 version is created in linux via electron-forge; I also tried creating versions for other operating systems and architectures

[npm run package (others)](https://pastebin.com/CbLARXSe)

**Expected behavior**
that the electron application worked, with the default settings described, without having to load and configure everything every time. I was hoping you could make it work like the [demo](https://github.com/frangoteam/frangoteam.github.io) so it would be lighter to use on a Raspberry Pi Zero W 2

**Screenshots**

## Test Default Electron App - Linux Desktop
![Screenshot_20240707_105504](https://github.com/frangoteam/FUXA/assets/410736/6ea295b8-5b33-4795-9ba6-2250fabbe412)

On Linux desktop it works but it is always empty, it doesn't load the project automatically, if I import it I have to fix something, I save and when I close and reopen the application it is completely empty.

## Test Electron App - Mac OS
<img width="468" alt="Schermata 2024-07-07 alle 10 41 33" src="https://github.com/frangoteam/FUXA/assets/410736/f7759e5a-88ee-408e-82c9-31c589bfe0b4">

## Test Electron App - Windows 11
![Screenshot 2024-07-07 104742](https://github.com/frangoteam/FUXA/assets/410736/05f437a9-ce42-4d37-847f-4676f8575b7c)

![Screenshot 2024-07-07 104825](https://github.com/frangoteam/FUXA/assets/410736/9d9131d3-4588-4968-abf7-efc423d7cd85)

on windows it remains blocked and does not start in both cases

## Test Electron App - Linux Arm64

I tried the application on: Raspberry Pi 4 4Gb with default image desktop and Raspberry Pi Zero W 2 with desktop xfce now I get the same error and it doesn't start

![Schermata 2024-07-07 alle 12 02 50 1](https://github.com/frangoteam/FUXA/assets/410736/84019be1-6bb3-425b-81bc-c351a2bbf70b)

**Environment**
 - FUXA version: latest
 - Node.js version: 16.20.2 (docker image version)
 - npm version: 8.19.4 (docker image version)
 - Platform/OS: Mac OS 10.15.7 
 - Browser: Chrome 125.0.6422.142 (x86_64)
