### ISSUE TITLE
[Question] How to add custom font style?

### ISSUE THREAD

**Issue by henjoe** [frangoteam/FUXA#1286]
I noticed that the font in the SVG editor is limited, I wonder if we can add more? like downloading the .tff and woff file putting it on a specific folder then it will be made available in the font-family options:

![image](https://github.com/user-attachments/assets/4de6ccc1-b9ea-4ddd-8fb5-80ce4c47df6b)

I tried to add a 7 segment font style under the
` src/assets/fonts/`
and try to `npm start` to the client folder, however I don't see the newly added fonts on the list. Maybe I just miss something here, can you guide us how to add custom font? 

Thank you.

Regards,

**Comment by LordNetro** [comment]
Hi @henjoe , 

You must add the font to `client\src\styles.css` and in the `client\src\app\_helpers\define.ts`:

Example adding **Saira-Bold**:
- styles.css
```css
@font-face {
    font-family: "Saira-Bold";
    src: local("Saira-Bold"),
        url("./assets/fonts/Saira/static/Saira-Bold.ttf")
            format("truetype");
}
```

- define.ts
```ts
static fonts = ['Sans-serif', 'Roboto-Thin', 'Roboto-Light', 'Roboto-Regular', 'Roboto-Medium', 'Roboto-Bold', 'Quicksand-Regular', 'Quicksand-Medium', 'Quicksand-Bold', 'Andria-Signature', 'Saira-Bold'];
```
![image](https://github.com/user-attachments/assets/316b6c68-d3c3-43ad-85ee-4228ed6d8dbc)

This is working for me, I hope it helps you :).
