### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zblack88** [frangoteam/FUXA#1420]
**Describe the bug**
When trying to create any script, I receive an "Unauthorized" error, but I have no authorization set, neither for the script, nor for the project.

>Http failure response for http://localhost:1881/api/runscript: 401 Unauthorized
>Unauthorized!

**To Reproduce**
Hard to say, on another machine with the same fuxa version worked correctly.

**Expected behavior**
write "ciao" on console

**Screenshots**
![image](https://github.com/user-attachments/assets/9b6f8a78-5458-40db-b32e-54555266b486)

**Environment**
 - FUXA version: 1.2.0-1922
 - Node.js version: v18.20.4 
 - npm version:
 - Platform/OS: Windows 10
 - Browser: Edge and Chrome

**Comment by unocelli** [comment]
Hi, check your installation or system
![script-test](https://github.com/user-attachments/assets/d52e1a33-3583-43fd-85e4-ffa8cb47c304)

**Comment by adnanebrahimi** [comment]
I had the same issue. To fix it, I removed the Docker volumes of Fuxa on the host and recreated the container. The issue has been resolved.

Here is my docker compose service of Fuxa:

 ```yml
 fuxa:
    image: frangoteam/fuxa:latest
    container_name: fuxa
    restart: always
    ports:
      - "1881:1881" 
    volumes:
      - './fuxa_volume/appdata:/usr/src/app/FUXA/server/_appdata'
      - './fuxa_volume/db:/usr/src/app/FUXA/server/_db'
      - './fuxa_volume/logs:/usr/src/app/FUXA/server/_logs'
      - './fuxa_volume/images:/usr/src/app/FUXA/server/_images' 
    depends_on:
      - influxdb
    networks:
      - iiot_network
```
